name: Test Inputs
on:
  workflow_dispatch:
    inputs:
      cuda_version:
        description: 'Test'
        required: true
        default: '12.8'
        type: choice
        options:
          - '12.8'
          - '13.0'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Inputs work"
